# Netlify configuration for redirects

[[redirects]]
  from = "/schedule"
  to = "/schedule.html"
  status = 200

[[redirects]]
  from = "/reviews"
  to = "/reviews.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/stories"
  to = "/stories.html"
  status = 200